# Generated by Django 3.0.7 on 2020-07-17 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_unidade', models.IntegerField(unique=True)),
                ('codigo', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('sigla', models.CharField(max_length=15, unique=True)),
                ('endereco', models.CharField(blank=True, max_length=250, null=True)),
                ('site', models.CharField(blank=True, max_length=250, null=True)),
                ('centro', models.CharField(max_length=200)),
                ('centro_sigla', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('sigla', models.CharField(max_length=25, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('descricao', models.TextField()),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='laboratorios.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='LinhaPesquisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('areaCNPQ', models.CharField(max_length=150)),
                ('subAreaCNPQ', models.CharField(max_length=150)),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorios.Laboratorio')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siape', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('formacao', models.CharField(max_length=50)),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='laboratorios.Departamento')),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
