# Generated by Django 3.0.7 on 2020-07-16 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labcoffee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='organizacao',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presentation',
            name='status',
            field=models.CharField(default='Planejado', max_length=15),
            preserve_default=False,
        ),
    ]
